In [1]:
import numpy as np

In [64]:
def sample(num=1,variates=None,dist='normal'): 
    """
    variates is a numpy arary in m*n
    where m is number of variables mean,variance for normal
    lamda for poison
    n = 1 or same as num
    dist can be normal or poison
    """
    if dist == 'normal':
        if variates.ndim == 1:
            return np.random.normal(loc=variates[0],scale=variates[1],size=num)
        elif variates.ndim == 2:
            return np.array([np.random.normal(loc=variates[i][0],scale=variates[i][1],size=num) for i in range(variates.shape[0])])
        else:
            print('for normal variates can be blah ')
        
    elif dist == 'poisson':
        pass
    else:
        pass
        

In [12]:
vari = np.array(((1,1),(1,2)))

In [16]:
vari.ndim

2

In [11]:
vari1 = np.array(((1,1)))

In [17]:
vari1.ndim

1

In [24]:
sample(5,vari,'normal')

array([[-0.48944538, -0.4050775 , -0.04974176,  0.58250997,  2.02148986],
       [ 2.71216519, -2.01314553,  5.5704412 ,  1.67436356,  3.7131774 ]])

In [25]:
sample(5,vari1,'normal')

array([ 1.13810253,  1.76305377, -0.208989  ,  0.96658569,  2.42042442])

In [60]:
vari3 = np.array([(np.random.randn(),np.abs(np.random.randn())) for i in range(15)])

In [61]:
vari3

array([[-0.24798021,  1.00517227],
       [-1.02562006,  0.39486901],
       [ 0.61230759,  0.15675861],
       [ 0.69505484,  0.43186854],
       [-0.77490919,  1.43894072],
       [ 0.59840896,  2.18566642],
       [ 1.96445877,  0.61435565],
       [ 0.2608541 ,  0.87945517],
       [ 0.38576686,  1.46952979],
       [ 0.67240749,  1.0276105 ],
       [ 0.19536421,  0.5685261 ],
       [-2.99375895,  0.42493416],
       [ 1.73592073,  0.62908046],
       [ 2.9134351 ,  0.57422048],
       [-0.669611  ,  1.44959783]])

In [65]:
sample(5,vari3,'normal')

array([[ 0.17158064,  0.59459815,  0.77512749,  0.2272634 ,  0.89479627],
       [-0.24884058, -0.83655439, -1.42406695, -0.36693365, -1.05065357],
       [ 0.49952905,  0.40109562,  0.52306388,  0.5024256 ,  0.39561773],
       [ 0.26423196,  1.00996095,  1.40204782,  0.50157449,  0.52060045],
       [ 2.29105611, -3.13581819, -0.03461337, -3.11370245, -1.63410854],
       [-1.35778722,  1.90723277,  1.72432382, -0.19680273,  2.94720771],
       [ 1.98318134,  2.46069803,  1.27118667,  2.50740022,  0.94036177],
       [-1.20953309,  0.49992882,  0.49853915,  0.9075576 ,  0.2256967 ],
       [ 0.42801964, -0.06485032, -1.12903552, -0.85564217, -0.80348024],
       [ 1.87666357, -0.72572199,  0.39650348,  0.83847035, -0.86016287],
       [ 0.83796124, -0.61432689,  0.06351116, -0.08038425, -0.13610586],
       [-2.59825158, -3.63561799, -1.99406018, -2.52804404, -3.53352844],
       [ 1.98064494,  1.05586503,  0.9359593 ,  1.86910224,  3.01375076],
       [ 2.94395759,  2.60556793,  2.2

this is a test 